### ISSUE TITLE
Fallback to another DNS server

### ISSUE THREAD

**Issue by Yengas** [nanopack/shaman#24]
I want to use shaman for overriding specific domains. Is there an option to forward DNS requests which weren't found in the shaman database to another DNS server?

If this is not planned, do you know if i can achieve the same effect by using OS settings?

**Comment by glinton** [comment]
Great idea, it was planned (as seen in [this comment](https://github.com/nanopack/shaman/blob/621dfa0f3e7c15fc69f794aa9ed13f970fd2841f/server/dns.go#L60)) but wasn't a priority at the time. I'll take a look at it again here soon, now that its been brought up here

**Comment by prologic** [comment]
+1
