### ISSUE TITLE
TTL doesn't decrement

### ISSUE THREAD

**Issue by glinton** [nanopack/shaman#30]
TTL doesn't decrement, but always shows the value that the domain was configured with
```sh
test.com.		30	IN	A	127.0.0.1
# sleep 5 && dig test.com
test.com.		30	IN	A	127.0.0.1
```

**Comment by abh** [comment]
That’s expected for an authoritative server. Why would it go down?

**Comment by glinton** [comment]
Hey good point! Thanks
