### ISSUE TITLE
Keep token enabled without ssl

### ISSUE THREAD

**Issue by PaluMacil** [nanopack/shaman#33]
I might want to terminate ssl on my reverse proxy exposed to the web but still have the DNS API protected by a token. Would splitting this insecure setting in two make sense to you? Or perhaps an empty token would mean none and the insecure should only mean ssl isn't used.

**Comment by glinton** [comment]
That's a great idea. It was likely pure oversight in the early stages of the project that was designed that way. I'll start working on that change.
